<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">New User</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('user/store')?>">
                            <div class="top-margin">
                                <label>Name <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->name?>" name="name" class="form-control" placeholder="Enter name">
                                <?= ErrMgr::bind('name') ?>
                            </div>
                            <div class="top-margin">
                                <label>Nif <span class="text-danger">*</span></label>
                                <input type="number" value="<?=$user->nif?>" name="nif" class="form-control" placeholder="Enter Nif">
                                <?= ErrMgr::bind('nif') ?>
                            </div>
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->username?>" name="username" class="form-control" placeholder="Enter Username">
                                <?= ErrMgr::bind('username') ?>
                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="password" value="<?=$user->password?>" name="password" class="form-control" placeholder="Enter Password">
                                <?= ErrMgr::bind('password') ?>
                            </div>
                            <div class="top-margin">
                                <label>Address <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->address?>" name="address" class="form-control" placeholder="Enter Address">
                                <?= ErrMgr::bind('address') ?>
                            </div>
                            <div class="top-margin">
                                <label>Telephone <span class="text-danger">*</span></label>
                                <input type="number" value="<?=$user->telephone?>" name="telephone" class="form-control" placeholder="Enter Telephone Nr">
                                <?= ErrMgr::bind('telephone') ?>
                            </div>
                            <div class="top-margin">
                                <label>Birthday Date <span class="text-danger">*</span></label>
                                <input type="date" value="<?=$user->birthday_date?>" name="birthday_date" class="form-control" placeholder="Enter Birthday Date">
                                <?= ErrMgr::bind('birthday_date') ?>
                            </div>
                            <div class="top-margin">
                                <label>Email <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->email?>" name="email" class="form-control" placeholder="Enter Email">
                                <?= ErrMgr::bind('email') ?>
                            </div>

                            <div class="top-margin">
                                <label>Role <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->role?>" name="role" class="form-control" placeholder="Enter Role">
                                <?= ErrMgr::bind('role') ?>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Register</button>
                            </div>
                            <div class="col-lg-4 text-left">
                                <a button class="btn btn-action" href="<?=Url::toRoute('user/index')?>">Return</a></button>                            </div>
                            </div>
                    </div>
                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>