<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>

<?php $user_logado = Data::get('user') ?>
<?php $users = Data::get('users') ?>

<?php if (!is_null($user_logado)){ ?>
<!-- container -->
<div class="container">
    <ol class="breadcrumb">
        <li><a href="../home/index">Home</a></li>
        <li class="active">User Index</li>
    </ol>
    <h2 class="text-left top-space">User Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                <?php if ($user_logado->role == 'admin'){ ?>
                 <th><h3>ID</h3></th>
                <?php } ?>
                <th><h3>Name</h3></th>
                <th><h3>Birthday Date</h3></th>
                <th><h3>Nif</h3></th>
                <th><h3>Username</h3></th>
                <th><h3>Address</h3></th>
                <th><h3>Telephone</h3></th>
                <th><h3>Email</h3></th>
                <?php if ($user_logado->role != 'user'){ ?>
                <th><h3>Role</h3></th>
                <?php } ?>
                <?php if ($user_logado->role == 'user'){ ?>
                 <th><h3>Points</h3></th>
                <?php } ?>

                </thead>

                <tbody>
                <?php if ($user_logado->role == 'admin'){ ?>
                    <?php foreach ($users as $user) { ?>
                        <?php if ($user->role != 'user') { ?>
                        <tr>
                            <td><?= $user->id_user ?></td>
                            <td><?= $user->name ?></td>
                            <td><?= \Carbon\Carbon::parse($user->birthday_date)->format('Y-m-d') ?> </td>
                            <td><?= $user->nif ?></td>
                            <td><?= $user->username ?></td>
                            <td><?= $user->address ?></td>
                            <td><?= $user->telephone ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->role ?></td>
                            <td>
                                <a href="<?= Url::toRoute('user/show', $user->id) ?>" class="btn btn-info btn-block"
                                   role="button">Show</a>
                                <a href="<?= Url::toRoute('user/edit', $user->id) ?>" class="btn btn-info btn-block"
                                   role="button">Edit</a>
                                <a href="<?= Url::toRoute('user/destroy', $user->id) ?>"
                                   class="btn btn-warning btn-block"
                                   role="button">Delete</a>
                            </td>
                        </tr>
                    <?php } ?>
                <?php } ?>
                <?php } ?>
                </tbody>

                <tbody>
                <?php if ($user_logado->role == 'user'){ ?>
                <?php foreach ($users as $user) { ?>
                    <?php if ($user_logado->id_user == $user->id_user){ ?>
                        <tr>
                            <td><?= $user->name ?></td>
                            <td><?= \Carbon\Carbon::parse($user->birthday_date)->format('Y-m-d') ?> </td>
                            <td><?= $user->nif ?></td>
                            <td><?= $user->username ?></td>
                            <td><?= $user->address ?></td>
                            <td><?= $user->telephone ?></td>
                            <td><?= $user->email ?></td>
                            <td><?= $user->points ?></td>

                            <td>
                                <a href="<?= Url::toRoute('user/show', $user->id) ?>" class="btn btn-info btn-block"
                                   role="button">Show</a>
                            </td>
                        </tr>
                        <?php } ?>
                    <?php } ?>
                <?php } ?>
                </tbody>
            </table>
            <div class="col-sm-6">
                <p>
                    <?php if ($user_logado->role == 'admin'){ ?>
                    <a href="<?= Url::toRoute('user/create') ?>" class="btn btn-info " role="button">New</a>
                    <?php } ?>
                    <button onclick="window.history.back()" class="btn btn-info " type="button">Return</button>
                </p>
            </div>
        </div>
    </div>
</div>
<?php } ?>

<?php Layout::includeLayout('footer') ?>







