<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>

<?php $user_logado = Data::get('user') ?>
<?php $users = Data::get('users') ?>

<!-- container -->
<div class="container">
    <?php if (!is_null($user_logado)){ ?>
    <?php if ($user_logado->role == 'admin'){ ?>
        <ol class="breadcrumb">
        <li><a href="../home/index">Home</a></li>
        <li class="active">User Index</li>
    </ol>
    <h2 class="text-left top-space">User Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>User ID</h3></th><th><h3>Name</h3></th><th><h3>Birthday Date</h3></th><th><h3>Nif</h3></th><th><h3>Username</h3></th><th><h3>Address</h3></th><th><h3>Telephone</h3></th><th><h3>Email</h3></th><th><h3>Role</h3></th></thead>
                <tbody>
                <?php foreach ($users as $user) { ?>
                <tr>
                    <td><?=$user->id_user?></td>
                    <td><?=$user->name?></td>
                    <td><?=$user->birthday_date?></td>
                    <td><?=$user->nif?></td>
                    <td><?=$user->username?></td>
                    <td><?=$user->address?></td>
                    <td><?=$user->telephone?></td>
                    <td><?=$user->email?></td>
                    <td><?=$user->role?></td>
                    <td>
                        <a href="<?=Url::toRoute('user/show', $user->id)?>" class="btn btn-info btn-block" role="button">Show</a>
                        <a href="<?=Url::toRoute('user/edit', $user->id)?>" class="btn btn-info btn-block" role="button">Edit</a>
                        <a href="<?=Url::toRoute('user/destroy', $user->id)?>" class="btn btn-warning btn-block" role="button">Delete</a>
                    </td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
            <div class="col-sm-6">
                <p>
                    <a href="../home/start" class="btn btn-info" role="button">Return</a>
                </p>
            </div>
        </div>
    </div>
</div>
    <div class="container">
    <?php } ?>
    <?php if ($user_logado->role == 'user'){ ?>
        <?php foreach ($users as $user) { ?>
        <?php if ($user_logado->id_user == $user->id_user){ ?>
    <ol class="breadcrumb">
        <li><a href="../home/index">Home</a></li>
        <li class="active">User Index</li>
    </ol>
    <h2 class="text-left top-space">User Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
    <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>User ID</h3></th><th><h3>Name</h3></th><th><h3>Birthday Date</h3></th><th><h3>Nif</h3></th><th><h3>Username</h3></th><th><h3>Address</h3></th><th><h3>Telephone</h3></th><th><h3>Email</h3></th><th><h3>Role</h3></th></thead>
            <tbody>
                <tr>
                    <td><?=$user->id_user?></td>
                    <td><?=$user->name?></td>
                    <td><?=$user->birthday_date?></td>
                    <td><?=$user->nif?></td>
                    <td><?=$user->username?></td>
                    <td><?=$user->address?></td>
                    <td><?=$user->telephone?></td>
                    <td><?=$user->email?></td>
                    <td><?=$user->role?></td>
                    <td>
                        <a href="<?=Url::toRoute('user/show', $user->id)?>" class="btn btn-info btn-block" role="button">Show</a>
                        <a href="<?=Url::toRoute('user/edit', $user->id)?>" class="btn btn-info btn-block" role="button">Edit</a>
                        <a href="<?=Url::toRoute('user/destroy', $user->id)?>" class="btn btn-warning btn-block" role="button">Delete</a>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="col-sm-6">
            <p>
                <a href="../home/start" class="btn btn-info" role="button">Return</a>
            </p>
        </div>
    </div>
    <?php } ?>
    <?php } ?>
    <?php } ?>
    </div> <!-- /row -->
    </div>	<!-- /container -->
        <?php } ?>
<?php Layout::includeLayout('footer')?>


