<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>


<!-- container -->
<div class="container">

    <div class="row">

        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Login</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('user/login')?>">
                            <div class="top-margin">
                                <label>Username <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->username?>" name="username" class="form-control" placeholder="Enter Username">
                                <?= ErrMgr::bind('username') ?>

                            </div>
                            <div class="top-margin">
                                <label>Password <span class="text-danger">*</span></label>
                                <input type="text" value="<?=$user->password?>" name="password" class="form-control" placeholder="Enter Password">
                                <?= ErrMgr::bind('password') ?>
                            </div>

                            <hr>
                            <div class="col-lg-6 text-right">
                                <button class="btn btn-action" type="submit">Login</button>
                            </div>
                            <div class="col-lg-6 text-left">
                                <button class="btn btn-action" type="submit">Register</button>
                            </div>
                    </div>

                    </form>
                </div>
            </div>

    </div>

    </article>
    <!-- /Article -->

</div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>