<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

<?php $user = Data::get('user') ?>
<?php $user_logado = Data::get('user_logado') ?>

<?php if(!is_null($user_logado)) {?>
    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">View User</h1>
                </header>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                                <?php if ($user_logado->role == 'admin' || $user_logado->role == 'gest') { ?>
                                    <div class="top-margin">
                                        <label>ID <span class="text-danger">*</span></label>
                                        <input readonly="true" type="text" value="<?= $user->id_user ?>" name="id_user"
                                               class="form-control">
                                    </div>
                                <?php } ?>
                                <div class="top-margin">
                                    <label>Name <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $user->name ?>" name="name"
                                           class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Birthday Date <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= \Carbon\Carbon::parse($user->birthday_date)->format('Y-m-d') ?>"
                                           name="birthday_date" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Nif <span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $user->nif ?>" name="nif"
                                           class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $user->username ?>" name="username"
                                           class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input readonly="true" type="password" value="<?= $user->password ?>"
                                           name="password" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Address <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $user->address ?>" name="address"
                                           class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Telephone <span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $user->telephone ?>"
                                           name="telephone" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $user->email ?>" name="email"
                                           class="form-control">
                                </div>
                            <div class="top-margin">
                                <label>Points <span class="text-danger">*</span></label>
                                <input readonly="true" type="number" value="<?= $user->points ?>" name="points"
                                       class="form-control">
                            </div>
                                 <?php if ($user_logado->role == 'admin') { ?>
                                <div class="top-margin">
                                    <label>Role <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $user->role ?>" name="role"
                                           class="form-control">
                                </div>
                                <?php }?>
                                <hr>
                                <div class="col-lg-4 text-right">
                                    <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
                                </div>
                        </div>
                    </div>
                </div>
        </div>
        </article>
        <!-- /Article -->
    </div>
    </div>    <!-- /container -->
<?php } ?>
<?php Layout::includeLayout('footer') ?>