<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $airport = Data::get('airport') ?>
<?php ErrMgr::attach($airport) ?>

    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
    <?php if ($user_logado->role == 'admin') { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Airport</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post"
                              action="<?= Url::toRoute('airport/update', $airport->id) ?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Name:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?= $airport->name ?>" class="form-control"
                                           name="name" placeholder="Enter Airport Name">
                                    <?= ErrMgr::bind('name') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Localization:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?= $airport->localization ?>"
                                           class="form-control" name="localization"
                                           placeholder="Enter Airport Localization">
                                    <?= ErrMgr::bind('localization') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Telephone:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?= $airport->telephone ?>"
                                           class="form-control" name="telephone" placeholder="Enter Airport Telephone">
                                    <?= ErrMgr::bind('telephone') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Email:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?= $airport->email ?>" class="form-control"
                                           name="email" placeholder="Enter Email Address">
                                    <?= ErrMgr::bind('email') ?>
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <a href="../index" class="btn btn-default" role="button">Return</a>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
    <?php } ?>
<?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>