<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $airports = Data::get('airports') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">Airport Index</li>
    </ol>

    <h2 class="text-left top-space">Airport Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>Airport ID</h3></th><th><h3>Localization</h3></th><th><h3>Telephone</h3></th><th><h3>Email</h3></th></thead>
                <tbody>
                <?php foreach ($airports as $airport) { ?>
                <tr>
                    <td><?=$airport->id_airport?></td>
                    <td><?=$airport->name?></td>
                    <td><?=$airport->localization?></td>
                    <td><?=$airport->telephone?></td>
                    <td><?=$airport->email?></td>



                    <td>
                        <a href="<?=Url::toRoute('user/show', $airport->id)?>" class="btn btn-info" role="button">Show</a>
                        <a href="<?=Url::toRoute('user/edit', $airport->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('user/destroy', $airport->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>
                </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Create a new Airport</h3>
            <p>
                <br>
                <a href="<?=Url::toRoute('airport/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>