<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $flight = Data::get('flight')?>
<?php ErrMgr::attach($flight) ?>


    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)){ ?>
    <?php if ($user_logado->role == 'admin' ||$user_logado->role == 'gest' ){ ?>
        <div class="row">
        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">New Flight</h1>
            </header>

            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?=Url::toRoute('flight/store')?>">
                                <div class="top-margin">
                                    <label>Airplane ID <span class="text-danger">*</span></label>
                                    <input type="number" value="<?=$flight->id_airplane?>" name="id_airplane" class="form-control" placeholder="Enter Airplane ID">
                                    <?= ErrMgr::bind('id_airplane') ?>
                                </div>
                            <div class="top-margin">
                                <label>Ticket Price <span class="text-danger">*</span></label>
                                <input type="number" value="<?=$flight->price?>" name="price" class="form-control" placeholder="Enter Ticket Price">
                                <?= ErrMgr::bind('price') ?>
                            </div>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Register</button>
                            </div>
                            <div class="col-lg-4 text-left">
                                <a button class="btn btn-action" href="<?=Url::toRoute('flight/index')?>">Return</a></button>                            </div>
                    </div>
                    </form>
                </div>
            </div>
    </div>
    </article>
    <!-- /Article -->
    </div>
<?php } ?>
<?php } ?>
    </div>	<!-- /container -->
<?php Layout::includeLayout('footer') ?>