<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $flight = Data::get('flight') ?>
<?php ErrMgr::attach($flight) ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Flight</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post"
                              action="<?= Url::toRoute('flight/update', $flight->id) ?>">
                                <?php if ($user_logado->role == 'gest') { ?>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Price:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"
                                    required value="<?= $flight->price ?>" class="form-control"
                                           name="price" placeholder="Enter Price">
                                    <?= ErrMgr::bind('price') ?>
                                </div>
                            </div>
                                <?php } ?>
                              <?php if ($user_logado->role == 'mark') { ?>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Discount:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number"  onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"
                                    required value="<?= $flight->discount ?>" class="form-control"
                                    name="discount" placeholder="Enter Discount">
                                    <?= ErrMgr::bind('discount') ?>
                                </div>
                            </div>
                              <?php } ?>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
<?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>