<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $flights = Data::get('flights') ?>

    <!-- container -->
    <div class="container">
        <?php if (!is_null($user_logado)) { ?>
            <?php if ($user_logado->role == 'gest' || $user_logado->role == 'op') { ?>
                <ol class="breadcrumb">
                    <li><a href="../home/index">Home</a></li>
                    <li class="active">Flight Index</li>
                </ol>
                <h2 class="text-left top-space">Flight Index</h2>
                <h2 class="top-space"></h2>
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-striped">
                            <thead>
                            <th><h3>ID</h3></th>
                            <th><h3>Ticket Price</h3></th>
                            </thead>
                            <tbody>
                            <?php foreach ($flights as $flight) { ?>
                                <tr>
                                    <td><?= $flight->id_flight ?></td>
                                    <td><?= $flight->price ?></td>
                                    <td>
                                        <a href="<?= Url::toRoute('flight/show', $flight->id) ?>" class="btn btn-info"
                                           role="button">Show</a>
            <?php if ($user_logado->role == 'gest' || $user_logado->role == 'op') { ?>
                <a href="<?= Url::toRoute('flight/ticketflight', $flight->id) ?>" class="btn btn-info"
                   role="button">Ticket</a>
            <?php } ?>
                                        <?php if ($user_logado->role == 'gest') { ?>
                                            <a href="<?= Url::toRoute('flight/edit', $flight->id) ?>"
                                               class="btn btn-info"
                                               role="button">Edit</a>
                                            <a href="<?= Url::toRoute('flight/destroy', $flight->id) ?>"
                                               class="btn btn-warning"
                                               role="button">Delete</a>
                                        <?php } ?>
                                        <?php if ($user_logado->role == 'admin' || $user_logado->role == 'gest') { ?>
                                            <a href="<?= Url::toRoute('stopover/stopovercreate', $flight->id) ?>"
                                               class="btn btn-info" role="button">Create Stopover</a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-sm-6">
                        <p>
                            <a href="<?= Url::toRoute('flight/create') ?>" class="btn btn-info" role="button">New</a>
                            <a href="../home/start" class="btn btn-info" role="button">Return</a>
                        </p>
                    </div>
                </div> <!-- /row -->
            <?php } ?>
        <?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>