<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $flights = Data::get('flights') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">Flight Index</li>
    </ol>

    <h2 class="text-left top-space">Flight Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>Flight ID</h3></th><th><h3>Airplane ID</h3></th><th><h3>Ticket Price</h3></th></thead>
                <tbody>
                <?php foreach ($flights as $flight) { ?>
                <tr>
                    <td><?=$flight->id_flight?></td>
                    <td><?=$flight->id_airplane?></td>
                    <td><?=$flight->price?></td>



                    <td>
                        <a href="<?=Url::toRoute('flight/show', $flight->id)?>" class="btn btn-info" role="button">Show</a>
                        <a href="<?=Url::toRoute('flight/edit', $flight->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('flight/destroy', $flight->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>
                </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Create a new Flight</h3>
            <br>
            <p>
                <a href="<?=Url::toRoute('flight/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>