<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $flight = Data::get('flight') ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
<?php if ($user_logado->role == 'gest'|| $user_logado->role == 'op' || $user_logado->role == 'mark') { ?>
        <div class="row">
        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">View Flight</h1>
            </header>
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form method="post" action="<?= Url::toRoute('flight/index') ?>">
                            <div class="top-margin">
                                <label>ID <span class="text-danger">*</span></label>
                                <input readonly="true" type="number" value="<?= $flight->id_flight ?>" name="id_flight"
                                       class="form-control">
                            </div>
                            <div class="top-margin">
                                <label>Ticket Price <span class="text-danger">*</span></label>
                                <input readonly="true" type="number" value="<?= $flight->price ?>" name="price"
                                       class="form-control">
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>Departure</th>
                                            <th>Return</th>
                                            <th>Departure Date</th>
                                            <th>Return Date</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($flight->stopovers as $stopover) { ?>
                                            <?= '<tr>' ?>
                                            <?= '<td>'.$stopover->departure_airport->localization.'</td>' ?>
                                            <?= '<td>'.$stopover->arrival_airport->localization.'</td>' ?>
                                            <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d').' '.$stopover->hour_of_departure.'</td>' ?>
                                            <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d').' '.$stopover->hour_of_arrival.'</td>' ?>
                                            <?='</tr>' ?>
                                        <?php } ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-action" type="submit">Return</button>
                            </div>
                            <?php if ($user_logado->role == 'gest') { ?>
                            <div class="col-lg-4 text-left">
                                <a href="<?= Url::toRoute('stopover/stopovercreate', $flight->id) ?>"
                                   class="btn btn-action" role="button">Create Stopover</a>
                            </div>
                            <?php } ?>
                    </div>
                    </form>
                </div>
            </div>
    </div>
    </article>
    <!-- /Article -->
    </div>
<?php } ?>
<?php } ?>
    </div>    <!-- /container -->

<?php Layout::includeLayout('footer') ?>