<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>

<?php $flight= Data::get('flight') ?>
<?php $user_logado = Data::get('user') ?>
<?php ErrMgr::attach($flight) ?>

    <div class="container">
<?php if (!is_null($user_logado)) { ?>
    <?php if ($user_logado->role == 'mark') { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Airplane</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post"
                              action="<?= Url::toRoute('flight/savediscount', $flight->id) ?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Price<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?= $flight->price ?>" class="form-control"
                                           name="price" placeholder="Enter Price">
                                    <?= ErrMgr::bind('price') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Discount<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?= $flight->discount ?>"
                                           class="form-control" name="discount" placeholder="Enter Discount">
                                    <?= ErrMgr::bind('discount') ?>
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
    <?php } ?>
<?php } ?>
    </div>    <!-- /container -->



<?php Layout::includeLayout('footer') ?>