<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $tickets = Data::get('tickets') ?>
<?php $id = Data::get('id') ?>



    <!-- container -->
    <div class="container">
        <?php if (!is_null($user_logado)) { ?>

            <ol class="breadcrumb">
                <li><a href="../home/index">Home</a></li>
                <li class="active">Ticket Index</li>
            </ol>
            <h2 class="text-left top-space">Ticket Index</h2>
            <h2 class="top-space"></h2>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-striped">
                        <thead>
                        <th><h3>Flight Nr.</h3></th>
                        <th><h3>Return Flight Nr.</h3></th>
                        <th><h3>Id Ticket</h3></th>
                        <th><h3>User ID</h3></th>
                        <th><h3>Passenger Name</h3></th>
                        <th><h3>Price</h3></th>
                        <th><h3>Date</h3></th>
                        <th><h3>Check-In Departure</h3></th>
                        <th><h3>Check-In Return</h3></th>
                        </thead>
                        <tbody>
                        <?php if ($user_logado->role == 'op' || $user_logado->role == 'mark') { ?>
                            <?php foreach ($tickets as $ticket) { ?>
                         <?php if ($ticket->departure_flight->id_flight == $id || $ticket->return_flight->id_flight == $id)  { ?>
                                <tr>
                                    <td><?= $ticket->id_departure_flight ?></td>
                                    <td><?= $ticket->id_return_flight ?></td>
                                    <td><?= $ticket->id_ticket ?></td>
                                    <td><?= $ticket->id_user ?></td>
                                    <td><?= $ticket->user->name ?></td>
                                    <td><?= $ticket->price ?></td>
                                    <td><?= \Carbon\Carbon::parse($ticket->date)->format('Y-m-d') ?> <?= $ticket->hour ?></td>
                                    <td><?php if ($ticket->check_in) echo('<i class="fa fa-check"></i>') ?></td>
                                    <td><?php if ($ticket->check_in_return) echo('<i class="fa fa-check"></i>') ?></td>
                                    <td>
                                        <a href="<?= Url::toRoute('ticket/show', $ticket->id) ?>"
                                           class="btn btn-info btn-block" role="button">Show</a>
                                        <a href="<?= Url::toRoute('ticket/edit', $ticket->id) ?>"
                                           class="btn btn-info btn-block" role="button">Edit</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php } ?>
                        <?php } ?>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-6">
                    <p>
                        <a href="../index" class="btn btn-info" role="button">Return</a>
                    </p>
                </div>
            </div> <!-- /row -->
        <?php } ?>

    </div>    <!-- /container -->

<?php Layout::includeLayout('footer') ?>