<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $stopover = Data::get('stopover') ?>
<?php $user_logado = Data::get('user') ?>
<?php ErrMgr::attach($stopover) ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
    <?php if ($user_logado->role == 'gest') { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Stopover</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post"
                              action="<?= Url::toRoute('stopover/update', $stopover->id) ?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Flight ID:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?= $stopover->id_flight ?>"
                                           class="form-control" name="id_flight" placeholder="Enter Flight ID">
                                    <?= ErrMgr::bind('id_flight') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?= $stopover->id_departure_airport ?>"
                                           class="form-control" name="id_departure_airport" placeholder="Enter Departure ID">
                                    <?= ErrMgr::bind('id_departure') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Price:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"  required value="<?= $stopover->price ?>"
                                           class="form-control" name="price"
                                           placeholder="Enter Price">
                                    <?= ErrMgr::bind('price') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Discount:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"  required value="<?= $stopover->discount ?>"
                                           class="form-control" name="discount"
                                           placeholder="Enter Discount">
                                    <?= ErrMgr::bind('discount') ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure Date:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="date" required value="<?= \Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d')  ?>"
                                           class="form-control" name="date_of_departure"
                                           placeholder="Enter Departure Date">
                                    <?= ErrMgr::bind('date_of_departure') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure Hour:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="time" required value="<?= $stopover->hour_of_departure ?>"
                                           class="form-control" name="hour_of_departure"
                                           placeholder="Enter Departure Hour">
                                    <?= ErrMgr::bind('hour_of_departure') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Arrival Date:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="date" required value="<?= \Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d') ?>"
                                           class="form-control" name="date_of_arrival" placeholder="Enter Arrival Date">
                                    <?= ErrMgr::bind('date_of_arrival') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Arrival Hour:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="time" required value="<?= $stopover->hour_of_arrival ?>"
                                           class="form-control" name="hour_of_arrival" placeholder="Enter Arrival Hour">
                                    <?= ErrMgr::bind('hour_of_arrival') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Distance:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?= $stopover->distance ?>"
                                           class="form-control" name="distance" placeholder="Enter Distance">
                                    <?= ErrMgr::bind('distance') ?>
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
    <?php } ?>
<?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>