<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $stopover = Data::get('stopover') ?>
<?php ErrMgr::attach($stopover) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Stopover</h1>
                </header>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('stopover/update', $stopover->id)?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Stopover ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$stopover->id_stopover?>" class="form-control" required name="id_stopover" placeholder="Enter Stopover ID">
                                    <?= ErrMgr::bind('id_stopover') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$stopover->id_departure?>" class="form-control" name="id_departure" placeholder="Enter Departure ID">
                                    <?= ErrMgr::bind('id_departure') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Destination ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$stopover->id_destination?>" class="form-control" name="id_destination" placeholder="Enter Destination ID">
                                    <?= ErrMgr::bind('id_destinnation') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure Hour:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="datetime-local" required value="<?=$stopover->hour_of_departure?>" class="form-control" name="hour_of_departure" placeholder="Enter Departure Hour">
                                    <?= ErrMgr::bind('hour_of_departure') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Arrival Hour:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="datetime-local" required value="<?=$stopover->hour_of_arrival?>" class="form-control" name="hour_of_arrival" placeholder="Enter Arrival Hour">
                                    <?= ErrMgr::bind('hour_of_arrival') ?>
                                </div>
                            </div>

                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>



        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>