<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $stopovers = Data::get('stopovers') ?>

<!-- container -->
<div class="container">
    <?php if (!is_null($user_logado)){ ?>
    <ol class="breadcrumb">
        <li><a href="../home/index">Home</a></li>
        <li class="active">Stopover Index</li>
    </ol>
    <h2 class="text-left top-space">Stopover Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>Stopover ID</h3></th><th><h3>Flight ID</h3></th><th><h3>Departure ID</h3></th><th><h3>Destination ID</h3></th><th><h3>Departure Hour</h3></th><th><h3>Arrival Hour</h3></th><th><h3>Distance</h3></th></thead>
                <tbody>
                <?php foreach ($stopovers as $stopover) { ?>
                <tr>
                    <td><?=$stopover->id_stopover?></td>
                    <td><?=$stopover->id_flight?></td>
                    <td><?=$stopover->id_departure?></td>
                    <td><?=$stopover->id_destination?></td>
                    <td><?=$stopover->hour_of_departure?></td>
                    <td><?=$stopover->hour_of_arrival?></td>
                    <td><?=$stopover->distance?></td>
                    <td>
                        <a href="<?=Url::toRoute('stopover/show', $stopover->id)?>" class="btn btn-info btn-block" role="button">Show</a>
                        <a href="<?=Url::toRoute('stopover/edit', $stopover->id)?>" class="btn btn-info btn-block" role="button">Edit</a>
                        <a href="<?=Url::toRoute('stopover/destroy', $stopover->id)?>" class="btn btn-warning btn-block" role="button">Delete</a>
                    </td>
                </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <p>
                <a href="<?=Url::toRoute('stopover/create')?>" class="btn btn-info" role="button">New</a>
                 <a href="../home/start" class="btn btn-info" role="button">Return</a>
            </p>
        </div>
    </div> <!-- /row -->
    <?php } ?>
</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>