<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>

<?php $user_logado = Data::get('user') ?>
<?php $stopover = Data::get('stopover') ?>
<?php $airports = Data::get('airports') ?>
<?php $flights = Data::get('flights') ?>
<?php $airplanes = Data::get('airplanes') ?>
<?php $id = Data::get('id') ?>

<?php ErrMgr::attach($stopover) ?>

    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
    <?php if ($user_logado->role == 'gest') { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">New Stopover</h1>
                </header>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>
                            <form method="post" action="<?= Url::toRoute('stopover/store') ?>">
                                <div class="top-margin">
                                    <label>Flight<span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $stopover->id_flight ?>"
                                           name="id_flight" class="form-control" placeholder=<?= $id ?>>
                                    <?= ErrMgr::bind('id_flight') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Departure<span class="text-danger">*</span></label>
                                    <select class="form-control" name="id_departure">
                                        <option value="">Select</option>
                                        <?php
                                        foreach ($airports as $key => $airport)
                                        {
                                            echo "<option value='" . $airport->id_airport . "'>$airport->localization</option>";

                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('id_departure') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Destination<span class="text-danger">*</span></label>
                                    <select class="form-control" name="id_destination">
                                        <option value="">Select</option>
                                        <?php

                                        foreach ($airports as $key => $airport)
                                        {
                                            echo "<option value='" . $airport->id_airport . "'>$airport->localization</option>";
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('id_destination') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Airplane<span class="text-danger">*</span></label>
                                    <select class="form-control" name="id_airplane">
                                        <option value="">Select</option>
                                        <?php

                                        foreach ($airplanes as $key => $airplane)
                                        {
                                            echo "<option value='" . $airplane->id_airplane . "'>$airplane->reference</option>";
                                        }
                                        ?>
                                    </select>
                                    <?= ErrMgr::bind('id_airplane') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Departure Date <span class="text-danger">*</span></label>
                                    <input type="date" value="<?= $stopover->date_of_departure ?>"
                                           name="date_of_departure" class="form-control"
                                           placeholder="Date of Departure">
                                    <?= ErrMgr::bind('date_of_departure') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Departure Hour <span class="text-danger">*</span></label>
                                    <input type="time" value="<?= $stopover->hour_of_departure ?>"
                                           name="hour_of_departure" class="form-control"
                                           placeholder="Enter Hour of Departure">
                                    <?= ErrMgr::bind('hour_of_departure') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Arrival Date<span class="text-danger">*</span></label>
                                    <input type="date" value="<?= $stopover->date_of_arrival ?>" name="date_of_arrival"
                                           class="form-control" placeholder="Enter Date of Arrival">
                                    <?= ErrMgr::bind('date_of_arrival') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Arrival Hour<span class="text-danger">*</span></label>
                                    <input type="time" value="<?= $stopover->hour_of_arrival ?>" name="hour_of_arrival"
                                           class="form-control" placeholder="Enter Hour of Arrival">
                                    <?= ErrMgr::bind('hour_of_arrival') ?>
                                </div>
                                <div class="top-margin">
                                    <label>Distance<span class="text-danger">*</span></label>
                                    <input type="number" value="<?= $stopover->distance ?>" name="distance"
                                           class="form-control" placeholder="Enter Distance">
                                    <?= ErrMgr::bind('distance') ?>
                                </div>
                                <hr>
                                <div class="col-lg-6 text-right">
                                    <button class="btn btn-action" type="submit">Register</button>
                                </div>
                                <div class="col-lg-6 text-left">
                                    <a button class="btn btn-action"
                                       href="<?= Url::toRoute('stopover/index') ?>">Return</a></button>
                                </div>
                        </div>
                    </div>
                    </form>
                </div>
        </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
    <?php } ?>
<?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>