<footer id="footer" class="top-space">

    <div class="footer1">
        <div class="container">
            <div class="row">

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Contact Us</h3>
                    <div class="widget-body">
                        <p>+351 9XXXXXXXX<br><br>
                            <a href="mailto:2201158@ipleiria.pt">Email</a>
                        </p>
                    </div>
                </div>

                <div class="col-md-3 widget">
                    <h3 class="widget-title">Follow Us</h3>
                    <div class="widget-body">
                        <p class="follow-me-icons">
                            <a href=""><i class="fa fa-twitter fa-2"></i></a>
                            <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                            <a href=""><i class="fa fa-github fa-2"></i></a>
                            <a href=""><i class="fa fa-facebook fa-2"></i></a>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p>We shall not cease from exploration, and the end of all our exploring will be to arrive
                            where we started and know the place for the first time.</p>
                    </div>
                    <h3 class="widget-title">T. S. Eliot</h3>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

    <div class="footer2">
        <div class="container">
            <div class="row">

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="simplenav">
                            <a href="#">Home</a> |
                            <a href="mailto:2201158@ipleiria.pt">Contact Us</a>
                        </p>
                    </div>
                </div>

                <div class="col-md-6 widget">
                    <div class="widget-body">
                        <p class="text-right">
                            Copyright &copy; 2016-2021,Flight Travel Air. <br> Site template by Sergey Pozhilov.
                        </p>
                    </div>
                </div>

            </div> <!-- /row of widgets -->
        </div>
    </div>

</footer>

<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php

use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;

?>

<?= AssetBundler::js() ?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>