<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $airplane = Data::get('airplane') ?>
<?php ErrMgr::attach($airplane) ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)){ ?>
    <?php if ($user_logado->role == 'admin' ||$user_logado->role == 'gest' ){ ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Airplane</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('airplane/update', $airplane->id)?>">
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Reference:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$airplane->reference?>" class="form-control" name="reference" placeholder="Enter Airplane Nr">
                                    <?= ErrMgr::bind('reference') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Type:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$airplane->airplanetype?>" class="form-control" name="airplanetype" placeholder="Enter Airplane Price">
                                    <?= ErrMgr::bind('airplanetype') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Lotation:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?=$airplane->lotation?>" class="form-control" name="lotation" placeholder="Enter Airplane Price">
                                    <?= ErrMgr::bind('lotation') ?>
                                </div>
                            </div>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <a href="../index" class="btn btn-default" role="button">Return</a>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
    </div>
<?php } ?>
<?php } ?>
    </div>	<!-- /container -->
<?php Layout::includeLayout('footer') ?>