<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $finances = Data::get('finances') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Finances Index</li>
        </ol>

        <h2 class="text-left top-space">Finances Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped">
                    <thead>
                    <th><h3>Id</h3></th>
                    <th><h3>Data</h3></th>
                    <th><h3>Valor</h3></th>
                    </thead>
                    <tbody>
                    <?php foreach ($finances as $finance) { ?>
                        <tr>
                            <td><?=$finance->id?></td>
                            <td><?=$finance->data?></td>
                            <td><?=$finance->valor?></td>
                            <td>
                               <a href="<?=Url::toRoute('finance/show', $finance->id)?>" class="btn btn-info" role="button">Show</a>
                                <a href="<?=Url::toRoute('finance/edit', $finance->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('finance/destroy', $finance->id)?>" class="btn btn-warning" role="button">Delete</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new Finance Record</h3>
                <p>
                    <a href="<?=Url::toRoute('finance/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>