<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $finances = Data::get('finance') ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">View Finances</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <hr>

                            <form method="post" action="<?=Url::toRoute('finance/index')?>">
                                <div class="top-margin">
                                    <label>Descricao<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$finances->descricao?>" name="name" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Tipo Categoria <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$finances->tipocategoria?>" name="isbn" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Valor <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$finances->valor?>" name="isbn" class="form-control">
                                </div>

                                <hr>

                                <div class="col-lg-4 text-right">
                                    <button class="btn btn-action" type="submit">Return</button>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>

        </div>

        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>