<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
    <!-- container -->
    <div class="container">
        <?php if (!is_null($user_logado)){ ?>

        <?php } ?>
    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>