<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $ticket = Data::get('ticket') ?>
<?php $user_logado = Data::get('user') ?>
<?php ErrMgr::attach($ticket) ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)){ ?>
    <div class="row">
        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">Edit Ticket</h1>
            </header>
            <div class="panel panel-default">
                <div class="panel-body">
                    <hr>
                    <?php if ($user_logado->role == 'admin' ){ ?>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">User ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" value="<?=$ticket->id_user?>" class="form-control" required name="id_user" placeholder="Enter User ID">
                                    <?= ErrMgr::bind('id_user') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure Flight ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?=$ticket->id_departure_flight?>" class="form-control" name="id_departure_flight" placeholder="Enter Departure Flight ID">
                                    <?= ErrMgr::bind('id_departure_flight') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Return Flight ID:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?=$ticket->id_return_flight?>" class="form-control" name="id_return_flight" placeholder="Enter Return Flight ID">
                                    <?= ErrMgr::bind('id_return_flight') ?>
                                </div>
                            </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="name">Ticket Price:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="number" required value="<?=$ticket->price?>" class="form-control" name="price" placeholder="Enter Ticket Price">
                                <?= ErrMgr::bind('price') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="name">Date:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="datetime-local" required value="<?=$ticket->date?>" class="form-control" name="date" placeholder="Enter Date">
                                <?= ErrMgr::bind('date') ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="name">Check-In:<span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="number" required value="<?=$ticket->check_in?>" class="form-control" name="check_in" placeholder="Enter Check-In Number">
                                <?= ErrMgr::bind('check_in') ?>
                            </div>
                        </div>
                        <hr>
                        <div class="col-lg-4 text-right">
                            <button class="btn btn-default" type="submit">Save</button>
                        </div>
                </div>
                </form>
                <?php } ?>
            </div>
    </div>
    </article>
    <!-- /Article -->
    </div>
<?php } ?>
    </div>	<!-- /container -->
<?php Layout::includeLayout('footer') ?>