<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $ticket = Data::get('ticket') ?>
<?php $user_logado = Data::get('user') ?>
<?php ErrMgr::attach($ticket) ?>
    <!-- container -->
    <div class="container">
<?php if (!is_null($user_logado)) { ?>
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Ticket</h1>
                </header>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                        <form class="form-horizontal" method="post"
                              action="<?= Url::toRoute('ticket/update', $ticket->id) ?>">
                                <?php if ($user_logado->role == 'op') { ?>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">User ID:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" value="<?= $ticket->id_user ?>" class="form-control" required
                                           name="id_user" placeholder="Enter User ID">
                                    <?= ErrMgr::bind('id_user') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Departure Flight ID:<span
                                            class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" required value="<?= $ticket->id_departure_flight ?>"
                                           class="form-control" name="id_departure_flight"
                                           placeholder="Enter Departure Flight ID">
                                    <?= ErrMgr::bind('id_departure_flight') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Return Flight ID:<span
                                            class="text-danger"></span></label>
                                <div class="col-sm-6">
                                    <input type="number" value="<?= $ticket->id_return_flight ?>" class="form-control"
                                           name="id_return_flight" placeholder="Enter Return Flight ID">
                                    <?= ErrMgr::bind('id_return_flight') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Price:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="number" onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"
                                           required value="<?= $ticket->price ?>" class="form-control"
                                           name="price" placeholder="Enter Ticket Price">
                                    <?= ErrMgr::bind('price') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Date:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="date" required value="<?= \Carbon\Carbon::parse($ticket->date)->format('Y-m-d') ?>" class="form-control"
                                           name="date" placeholder="Enter Date">
                                    <?= ErrMgr::bind('date') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Hour:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="time" required value="<?= $ticket->hour ?>" class="form-control"
                                           name="hour" placeholder="Enter Hour">
                                    <?= ErrMgr::bind('hour') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Check-In:<span
                                            class="form-check-label"></span></label>
                                <div class="col-sm-6">
                                    <select class="form-control" name="check_in">
                                        <option></option>
                                        <option value="1" <?php if ($ticket->check_in == 1) echo('selected'); ?>>Yes
                                        </option>
                                        <option value="0" <?php if ($ticket->check_in == 0) echo('selected'); ?>>No
                                        </option>
                                    </select>
                                    <?= ErrMgr::bind('check_in') ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Check-In Return:<span
                                            class="form-check-label"></span></label>
                                <div class="col-sm-6">
                                    <select class="form-control" name="check_in_return">
                                        <option></option>
                                        <option value="1" <?php if ($ticket->check_in_return == 1) echo('selected'); ?>>
                                            Yes
                                        </option>
                                        <option value="0" <?php if ($ticket->check_in_return == 0) echo('selected'); ?>>
                                            No
                                        </option>
                                    </select>
                                </div>
                            </div>
                                <?php } ?>
                            <?php if ($user_logado->role == 'mark') { ?>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="name">Discount:<span class="text-danger">*</span></label>
                                    <div class="col-sm-6">
                                        <input type="number" onchange="setTwoNumberDecimal" min="0" max="100000" step="0.01"
                                               required value="<?= $ticket->discount_value ?>" class="form-control"
                                               name="discount_value" placeholder="Enter Discount Value">
                                        <?= ErrMgr::bind('discount_value') ?>
                                    </div>
                                </div>
                            <?php } ?>
                            <hr>
                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                                <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>
        </article>
        <!-- /Article -->
        </div>
<?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>