<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $tickets = Data::get('tickets') ?>

<!-- container -->
<div class="container">

    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">Ticket Index</li>
    </ol>

    <h2 class="text-left top-space">Ticket Index</h2>
    <h2 class="top-space"></h2>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped"><thead><th><h3>User ID</h3></th><th><h3>Flight Number ID</h3></th><th><h3>Departure Flight ID</h3></th><th><h3>Return Flight ID</h3></th><th><h3>Price</h3></th><th><h3>Date</h3></th><th><h3>Check-In Number</h3></th></thead>
                <tbody>
                <?php foreach ($tickets as $ticket) { ?>
                <tr>
                    <td><?=$ticket->id_user?></td>
                    <td><?=$ticket->id_flight_number?></td>
                    <td><?=$ticket->id_departure_flight?></td>
                    <td><?=$ticket->id_return_flight?></td>
                    <td><?=$ticket->price?></td>
                    <td><?=$ticket->date?></td>
                    <td><?=$ticket->check_in?></td>


                    <td>
                        <a href="<?=Url::toRoute('ticket/show', $ticket->id)?>" class="btn btn-info" role="button">Show</a>
                        <a href="<?=Url::toRoute('ticket/edit', $ticket->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('ticket/destroy', $ticket->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>


                </tr>
                <?php } ?>

                </tbody>

            </table>

        </div>
        <div class="col-sm-6">
            <h3>Create a new Ticket</h3>
            <br>
            <p>
                <a href="<?=Url::toRoute('ticket/create')?>" class="btn btn-info" role="button">New</a>
            </p>
        </div>
    </div> <!-- /row -->

</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>