<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header') ?>
<?php $user_logado = Data::get('user') ?>
<?php $ticket = Data::get('ticket') ?>
<?php $stopovers = Data::get('stopovers') ?>
<?php $airports = Data::get('airports') ?>


    <!-- container -->
    <div class="container">
        <?php if (!is_null($user_logado)) { ?>
    <div class="row">
        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">View Ticket</h1>
            </header>
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <hr>
                            <?php if ($user_logado->role == 'op' || $user_logado->role == 'gest') { ?>
                                <div class="top-margin">
                                    <label>ID <span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $ticket->id_ticket ?>"
                                     name="id_ticket" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>User ID <span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $ticket->id_user ?>" name="user"
                                     class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>User Name <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= $ticket->user->name ?>" name="name"
                                    class="form-control">
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table table-striped">
                                            <thead>
                                            <tr>
                                                <th>Departure</th>
                                                <th>Return</th>
                                                <th>Departure Date</th>
                                                <th>Return Date</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td colspan="4"><b>Departure Flight(s)</b></td>
                                            </tr>
                                                <?php foreach ($ticket->departure_flight->stopovers as $stopover) { ?>
                                                    <?= '<tr>' ?>
                                                        <?= '<td>'.$stopover->departure_airport->localization.'</td>' ?>
                                                        <?= '<td>'.$stopover->arrival_airport->localization.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d').' '.$stopover->hour_of_departure.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d').' '.$stopover->hour_of_arrival.'</td>' ?>
                                                    <?='</tr>' ?>
                                                <?php } ?>
                                                <?php if($ticket->return_flight != null) { ?>
                                                    <tr>
                                                        <td colspan="4"><b>Arrival Flight(s)</b></td>
                                                    </tr>
                                                    <?php foreach ($ticket->return_flight->stopovers as $stopover) { ?>
                                                        <?= '<tr>' ?>
                                                        <?= '<td>'.$stopover->departure_airport->localization.'</td>' ?>
                                                        <?= '<td>'.$stopover->arrival_airport->localization.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d').' '.$stopover->hour_of_departure.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d').' '.$stopover->hour_of_arrival.'</td>' ?>
                                                        <?='</tr>' ?>
                                                        <?php } ?>
                                                <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="top-margin">
                                    <label>Ticket Price <span class="text-danger">*</span></label>
                                    <input readonly="true" type="number" value="<?= $ticket->price ?>" name="price"
                                     class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Date <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?= \Carbon\Carbon::parse($ticket->date)->format('Y-m-d') ?>"
                                     name="date" class="form-control">
                                </div>
                                <div class="top-margin">
                                    <label>Check-In <span class="text-info"></span></label>
                                    <td class="form-control"
                                        readonly="true"><?php if ($ticket->check_in) echo('<i class="fa fa-check"></i>') ?></td>
                                </div>
                                <div class="top-margin">
                                    <label>Check-In Return <span class="text-info"></span></label>
                                    <td class="form-control"
                                    readonly="true"><?php if ($ticket->check_in_return) echo('<i class="fa fa-check"></i>') ?></td>
                                </div>
                                <hr>
                            <?php } ?>

                            <?php if ($user_logado->role == 'user') { ?>
                                <?php if ($ticket->id_user == $user_logado->id_user) { ?>
                                    <div class="top-margin">
                                        <label>Passenger Name <span class="text-danger">*</span></label>
                                        <input readonly="true" type="text" value="<?= $ticket->user->name ?>"
                                         name="name" class="form-control">
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <table class="table table-striped">
                                                <thead>
                                                <tr>
                                                    <th>Departure</th>
                                                    <th>Return</th>
                                                    <th>Departure Date</th>
                                                    <th>Return Date</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                <tr>
                                                    <td colspan="4"><b>Departure Flight(s)</b></td>
                                                </tr>
                                                <?php foreach ($ticket->departure_flight->stopovers as $stopover) { ?>
                                                    <?= '<tr>' ?>
                                                    <?= '<td>'.$stopover->departure_airport->localization.'</td>' ?>
                                                    <?= '<td>'.$stopover->arrival_airport->localization.'</td>' ?>
                                                    <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d').' '.$stopover->hour_of_departure.'</td>' ?>
                                                    <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d').' '.$stopover->hour_of_arrival.'</td>' ?>
                                                    <?='</tr>' ?>
                                                <?php } ?>
                                                <?php if($ticket->return_flight != null) { ?>
                                                    <tr>
                                                        <td colspan="4"><b>Arrival Flight(s)</b></td>
                                                    </tr>
                                                    <?php foreach ($ticket->return_flight->stopovers as $stopover) { ?>
                                                        <?= '<tr>' ?>
                                                        <?= '<td>'.$stopover->departure_airport->localization.'</td>' ?>
                                                        <?= '<td>'.$stopover->arrival_airport->localization.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_departure)->format('Y-m-d').' '.$stopover->hour_of_departure.'</td>' ?>
                                                        <?= '<td>'.\Carbon\Carbon::parse($stopover->date_of_arrival)->format('Y-m-d').' '.$stopover->hour_of_arrival.'</td>' ?>
                                                        <?='</tr>' ?>
                                                    <?php } ?>
                                                <?php } ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="top-margin">
                                        <label>Ticket Price <span class="text-danger">*</span></label>
                                        <input readonly="true" type="number" value="<?= $ticket->price ?>" name="price"
                                         class="form-control">
                                    </div>
                                    <div class="top-margin">
                                        <label>Date <span class="text-danger">*</span></label>
                                        <input readonly="true" type="datetime-local" value="<?= $ticket->date ?>"
                                         name="date" class="form-control">
                                    </div>
                                    <div class="top-margin">
                                        <label>Check-In <span class="text-danger"></span></label>
                                        <td class="form-control"
                                        readonly="true"><?php if ($ticket->check_in) echo('<i class="fa fa-check"></i>') ?></td>
                                    </div>
                                    <div class="top-margin">
                                        <label>Check-In Return <span class="text-danger"></span></label>
                                        <td class="form-control"
                                        readonly="true"><?php if ($ticket->check_in_return) echo('<i class="fa fa-check"></i>') ?></td>
                                    </div>
                                    <hr>
                                <?php } ?>
                            <?php } ?>

                            <div class="col-lg-4 text-right">
<!--                                <a class="btn btn-action" href="--><?//= Url::toRoute('ticket/index') ?><!--">Return</a>-->
                                <button onclick="window.history.back()" class="btn btn-info" type="button">Return</button>
                            </div>
                    </div>
                </div>
            </div>
    </div>
    </article>
    <!-- /Article -->
    </div>
    <?php } ?>
    </div>    <!-- /container -->

<?php Layout::includeLayout('footer') ?>