<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('indexheader');
$user_logado = Data::get('user');
$ticket = Data::get('ticket');

?>

    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                <?php echo($ticket->id_ticket); ?>
            </div>
        </div>

    </div>



    <div class="col-sm-6">
        <p>
            <a href="/weblogicmvc/webapp/flight/index" class="btn btn-info" role="button">Return</a>
        </p>
    </div>

<?php Layout::includeLayout('footer') ?>

<?php


