<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('indexheader');
$user_logado = Data::get('user');
$ticket = Data::get('ticket');

?>
    <div class="container">
        <div class="row" style="min-height: 200px;">
            <div class="com-md-12">
                <h1>Discount</h1>
                <table class="table">
                    <thead>
                    <th>Flight</th>
                    <th>Ticket</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Final Price</th>

                    </thead>
                    <tbody>
                        <tr>
                            <td><?= $ticket->departure_flight->id_flight ?></td>
                            <td><?= $ticket->id_ticket ?></td>
                            <td><?= $ticket->price ?></td>
                            <td><?= $ticket->price * 0.15?>$ - 15% of discount' </td>
                            <td><?= $ticket->price - $ticket->price * 0.15?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="col-sm-6">
        <p>
            <a href="/weblogicmvc/webapp/flight/index" class="btn btn-info" role="button">Return</a>
        </p>
    </div>

<?php Layout::includeLayout('footer') ?>

<?php


