<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header');

$user_logado = Data::get('user');
$id_flight = Data::get('id_flight');
$id_ticket = Data::get('id_ticket');
$id_flight_return = Data::get('id_flight_return');
$price = Data::get('price');
$qtt = Data::get('qtt');
?>
    <!-- container -->
    <div class="container">
        <?php if (!is_null($user_logado)) { ?>
            <div class="container">
                <div class="row">
                    <div class="com-md-12">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">ID Ticket</th>
                                <th scope="col">ID Voo de Ida</th>
                                <th scope="col">ID Voo de Volta</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Preço</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th><?php echo $id_ticket ?></th>
                                <th><?php echo $id_flight ?></th>
                                <th><?php echo $id_flight_return ?></th>
                                <th><?php echo $qtt ?></th>
                                <th><?php echo $price ?></th>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <button onclick="window.history.back()" class="btn btn-default " type="button">Return</button>
            </div>
        <?php } ?>
    </div>    <!-- /container -->
<?php Layout::includeLayout('footer') ?>