<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header');
$error = Data::get('error');
$user_logado = Data::get('user');
?>

<?php if (!is_null($user_logado)) { ?>

    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                <?php echo($error); ?>
            </div>
        </div>

    </div>



<?php } ?>

<div class="col-sm-6">
    <p>
        <a href="../home/start" class="btn btn-info" role="button">Return</a>
    </p>
</div>

<?php Layout::includeLayout('footer') ?>

