<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
Layout::includeLayout('header');
$user_logado = Data::get('user');
$flight = Data::get('flight');
$stopovers = Data::get('stopovers');
$origin = Data::get('origin');
$destination = Data::get('destination');
?>
<!-- container -->
<div class="container">
    <?php if (!is_null($user_logado)){ ?>
        <div class="container">
            <div class="row">
                <div class="com-md-12">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Flight Ref.</th>
                            <th scope="col">Origin</th>
                            <th scope="col">Destination</th>
                            <th scope="col">Price</th>

                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <th><?php echo $flight->id_flight?></th>
                            <th><?php echo $origin->name?></th>
                            <?php if(!is_null($destination)) { ?>
                            <th><?php echo $destination->name?></th>
                            <?php } ?>
                            <th><?php echo $flight->price?></th>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <a href="../index" class="btn btn-info" role="button">Return</a>
        </div>
    <?php } ?>
</div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>


