<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('indexheader');
$user_logado = Data::get('user');
$date = Data::get('date');
$date_return = Data::get('date_return');
$result = Data::get('result');
$result_return = Data::get('result_return');
$flight = Data::get('flight');
$destiny = Data::get('destiny');
ErrMgr::attach($flight);
?>


    <!-- Header -->
    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <!--<div class="row">
                <img src="../../../public/img/logo2.png" style="width:200px;height:200px;>
            </div>
            <div class="row">-->
                <h2>Flight Travel Air<br></h2>
            <div class="row">
            <form method="post" action="<?=Url::toRoute('home/index')?>">
                <select name="flight">
                    <option value="" <?php if($flight == '') echo 'selected' ?>>Select</option>
                    <option value="Porto" <?php if($flight == 'Porto') echo 'selected' ?>>Porto</option>
                    <option value="Lisboa" <?php if($flight == 'Lisboa') echo 'selected' ?>>Lisboa</option>
                    <option value="Faro" <?php if($flight == 'Faro') echo 'selected' ?>>Faro</option>
                    <option value="Açores" <?php if($flight == 'Açores') echo 'selected' ?>>Açores</option>
                    <option value="New Deli" <?php if($flight == 'New Deli') echo 'selected' ?>>New Deli</option>
                    <option value="New York" <?php if($flight == 'New York') echo 'selected' ?>>New York</option>
                    <option value="Washington" <?php if($flight == 'Washington') echo 'selected' ?>>Washington DC</option>
                </select>
                <select name="destiny">
                    <option value="" <?php if($destiny == '') echo 'selected' ?>>Select</option>
                    <option value="Porto" <?php if($destiny == 'Porto') echo 'selected' ?>>Porto</option>
                    <option value="Lisboa" <?php if($destiny == 'Lisboa') echo 'selected' ?>>Lisboa</option>
                    <option value="Faro" <?php if($destiny == 'Faro') echo 'selected' ?>>Faro</option>
                    <option value="Açores" <?php if($destiny == 'Açores') echo 'selected' ?>>Açores</option>
                    <option value="New Deli" <?php if($destiny == 'New Deli') echo 'selected' ?>>New Deli</option>
                    <option value="New York" <?php if($destiny == 'New York') echo 'selected' ?>>New York</option>
                    <option value="Washington" <?php if($destiny == 'Washington') echo 'selected' ?>>Washington DC</option>
                </select>
                <input type="date" name="date" <?php if($date != '')  echo 'value="'.$date.'"' ?>  required/>
                <input type="date" name="date_return" <?php if($date_return != '')  echo 'value="'.$date_return.'"' ?>/>
                <input type="submit" value="Search"/>
                </form>
            </div>
            <br>
        </div>
    </header>


    <form method="post" action="<?=Url::toRoute('home/buy')?>">
        <div class="container">
            <div class="row" style="min-height: 200px;">
                <div class="com-md-12">
                <h1>One Side</h1>
                    <table class="table">
                        <tbody>
                        <?php foreach ($result as $value) { ?>
                            <tr>
                            <td>
                                <td><input type="radio" id="id_flight" name="id_flight" value="<?php echo $value->id_flight ?>"></td>
                                <td><a href="<?php echo 'flightdetail/?idF='. $value->id_flight .'&or='. $flight.'&dest='. $destiny .'' ?> " class="btn btn-sm btn-success"><i class="fa fa-plane"></i></a></td>
                                <td><?=$value->reference?></td>
                                <td><?=$flight?></td>
                                <td><?=$destiny?></td>
                                <td><?=$value->date_of_departure?> <?=$value->hour_of_departure?></td>
                                <td><?=$value->date_of_arrival?> <?=$value->hour_of_arrival?></td>
                                <td><?=$value->price?> €</td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row" style="min-height: 200px;">
                <div class="com-md-12">
                <h1>Return</h1>
                    <table class="table">
                        <tbody>
                        <?php foreach ($result_return as $value) { ?>
                            <tr>
                            <td>
                                <td><input type="radio" id="id_flight_return" name="id_flight_return" value="<?php echo $value->id_flight ?>"></td>
                                <td><a href="<?php echo 'flightdetail/?idF='. $value->id_flight .'&or='. $destiny.'&dest='. $flight .'' ?> " class="btn btn-sm btn-success"><i class="fa fa-plane"></i></a></td>
                                <td><?=$value->reference?></td>
                                <td><?=$destiny?></td>
                                <td><?=$flight?></td>
                                <td><?=$value->date_of_departure?> <?=$value->hour_of_departure?></td>
                                <td><?=$value->date_of_arrival?> <?=$value->hour_of_arrival?></td>
                                <td><?=$value->price?> €</td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row" style="min-height: 200px;">
                <div class="com-md-12">
                    <label>Quantidade</label>
                    <input type="number" name="qtt"  placeholder="1" required/>
                </div>
                <div class="com-md-12" style="margin-top: 5vh;">
                    
                    <input type="submit" value="Buy" class="btn btn-primary"/>
                </div>
            </div>
        </div>
    </form>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>