<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>

    <!-- Header -->
    <header id="head">
        <div class="container">
            <div class="row">
                <h2>Flight Travel Air<br></h2>
                <br>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('user/create')?>">Register Now</a></p>
            </div>
        </div>
    </header>
    <!-- /Header -->



<?php Layout::includeLayout('footer')?>