<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use Carbon\Carbon;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$user = Data::get('user');
$flight = Data::get('flight');
$result = Data::get('result');
ErrMgr::attach($flight);
?>
    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <h2>Flight Travel Air<br></h2>
                <br>
                    <h1>Flight Result</h1>
                    <br>
                    <form method="post" action="<?=Url::toRoute('home/searchflight')?>">
                        <h1>SEARCH FOR FLIGHTS</h1>
                        <input type="text" name="flight" value="<?php $flight ?>" required/>
                        <input type="submit" value="Search"/>
                    </form>
                    <br>
                <table class="table table-striped"><thead><th><h3>Flight/h3></th> </thead>
                    <tbody>
                    <?php foreach ($result as $value) { ?>
                    <tr>
                        <td><a href="/comprar?flight=1(id_flight)">Buy</a></td>
                        <td><?=$value->id_flight?></td>
                        <td><?=$value->id_airplane?></td>
                        <td><?=$value->price?></td>
                    </tr>
                    </tbody>
                <?php } ?>

                    <br>

            </div>
        </div>
    </header>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>
