<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use Carbon\Carbon;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$user = Data::get('user');
$date = Data::get('date');
$date2 = Data::get('date2');
$result = Data::get('result');
$flight = Data::get('flight');
ErrMgr::attach($flight);
?>
    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <h2>Flight Travel Air<br></h2>
                <br>
                    <h1>Flight Result</h1>
                    <br>
                    <form method="post" action="<?=Url::toRoute('home/searchflight')?>">
                        <h1>SEARCH FOR FLIGHTS</h1>
                        <input type="text" name="flight" value="<?php $flight ?>" required/>
                        <input type="date" name="date" value="<?php $date ?>" required/>
                        <input type="date" name="date2" value="<?php $date2 ?>" required/>
                        <input type="submit" value="Search"/>
                    </form>
                    <br>
                    <tbody>
                        <?php foreach ($result as $value) { ?>
                    <tr>
                        <td><?=$value->origin?></td>
                        <td><?=$value->destination?></td>
                        <td><?=$value->price?></td>
                    </tr>
                    </tbody>
                <?php } ?>
            </div>
        </div>
        <br>
    </header>
    <!-- /Header -->

<?php Layout::includeLayout('footer')?>
