<?php
use ArmoredCore\Controllers\BaseController;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\View;
use Carbon\Carbon;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header');
$user = Data::get('user');
$date = Data::get('date');
$date2 = Data::get('date2');
$result = Data::get('result');
$flight = Data::get('flight');
ErrMgr::attach($flight);
?>
    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Flight Travel Air<br></h2>
                    <br>
                    <h1>Flight Result</h1>
                    <br>
                    <form method="post" action="<?=Url::toRoute('home/searchflight')?>">
                        <select name="flight" required>
                            <option value="Select">Select</option>
                            <option value="Porto">Porto</option>
                            <option value="Lisboa">Lisboa</option>
                            <option value="Açores">Açores</option>
                            <option value="New Deli">New Deli</option>
                            <option value="New York">New York</option>
                            <option value="Washington">Washington DC</option>
                        </select>
                        <input type="date" name="date" required/>
                        <input type="date" name="date2" required/>
                        <input type="submit" value="Search"/>
                    </form>
                </div>
        </div>
        <br>
    </header>
    <!-- /Header -->
<div class="container">
    <div class="row">
        <div class="com-md-12">
            <table class="table">
                <tbody>
                <?php foreach ($result as $value) { ?>
                    <tr>
                        <td><a href="#" class="btn btn-sm btn-success"><i class="fa fa-plane"></i></a></td>
                        <td><?=$value->reference?></td>
                        <td><?=$value->origin?></td>
                        <td><?=$value->destination?></td>
                        <td><?=$value->date_of_departure?> <?=$value->hour_of_departure?></td>
                        <td><?=$value->date_of_arrival?> <?=$value->hour_of_arrival?></td>
                        <td><?=$value->price?> €</td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>

</div>

<?php Layout::includeLayout('footer')?>
