<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;
Layout::includeLayout('header');
$user_logado = Data::get('user')
?>


    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <h1>User Details</h1><br>
            </div>
        </div>
    </header>
<?php if (!$user_logado == null){?>
<table class="table table-striped">
    <thead>
    <tr>
        <th  scope="col"> <?= !is_null($user_logado) ? 'NAME: ' .$user_logado->name.' <br><br> ROLE:  '. $user_logado->role : '' ?></th?>
    </tr>
    </thead>
    <?php if ($user_logado->role == 'admin' ){ ?>
    <tbody>
    <tr>
        <td><p><a href="../user/index" class="text-primary">User Index</a></p></td>
        <td><p><a href="../ticket/index" class="text-primary">Ticket Index</a></p></td>
        <td><p><a href="../flight/index" class="text-primary">Flight Index</a></p></td>
        <td><p><a href="../stopover/index" class="text-primary">Stopover Index</a></p></td>
        <td><p><a href="../airport/index" class="text-primary">Airport Index</a></p></td>
        <td><p><a href="../airplane/index" class="text-primary">Airplane Index</a></p></td>
    </tr>
    </tbody>
    <?php } ?>

</table>
<?php } ?>

<?php Layout::includeLayout('footer') ?>

"<td><a href='http://yourlink'>delete</a></td>";
