<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;
Layout::includeLayout('header');
$user_logado = Data::get('user')
?>


    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <h2>Flight Travel Air<br></h2>
                <br>
                    <h1>User Details</h1><br>

                    <h5><?= !is_null($user_logado) ? 'NAME: ' .$user_logado->name.' <br><br> ROLE:  '. $user_logado->role : '' ?></h5>

                <?php if (!$user_logado == null){?>
        <?php if ($user_logado->role == 'admin' ){ ?>
            <a href="../user/index">User Index</a><br>
            <a href="../ticket/index">Ticket Index</a><br>
            <a href="../stopover/index">Stopover Index</a><br>
            <a href="../flight/index">Flight Index</a><br>
            <a href="../airport/index">Airport Index</a><br>
            <a href="../airplane/index">Airplane Index</a><br>
        <?php } ?>
                <?php if ($user_logado->role != 'admin') { ?>
            <a href="../user/show">User Show </a><br>
            <a href="../ticket/show">Ticket Show </a><br>
            <a href="../stopover/show">Stopover Show </a><br>
            <a href="../flight/show">Flight Show</a><br>
            <a href="../airport/show">Airport Show </a><br>
            <a href="../airplane/show">Airplane Show</a><br>
        <?php }?>
                <?php } ?>
                <br>
            </div>
        </div>
    </header>

<?php Layout::includeLayout('footer') ?>