<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;

Layout::includeLayout('header');
$user = Data::get('user')
?>


    <header id="head">
        <link rel="stylesheet" type="text/css" href="../layout/style/mystyle.css"/>
        <div class="container">
            <div class="row">
                <h2>Flight Travel Air<br></h2>
                <br>
                    <h1>User Details</h1><br>

                    <h5><?= !is_null($user) ? 'NAME: ' .$user->name.' <br><br> ROLE:  '. $user->role : '' ?></h5>
                <br>
            </div>
        </div>
    </header>

<?php Layout::includeLayout('footer') ?>