<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('usererrorheader');
$error_message = Data::get('error_message');
?>

    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                <?php echo($error_message); ?>
            </div>
        </div>

    </div>



    <div class="col-sm-6">
        <p>
            <a href="../home/start" class="btn btn-info" role="button">Return</a>
        </p>
    </div>

<?php Layout::includeLayout('footer') ?>

<?php
