<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('usererrorheader');
$error = Data::get('error');
?>

    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger" role="alert">
                <?php echo($error); ?>
            </div>
        </div>

    </div>



    <div class="col-sm-6">
        <p>
            <button onclick="window.history.back()" class="btn btn-info " type="button">Return</button>
        </p>
    </div>

<?php Layout::includeLayout('footer') ?>

<?php
