<html>
<body>
<head>
    <title>User Registration</title>
</head>
<form action="welcome.php" method="post">
    Name: <input type="text" name="name"><br>
    E-mail: <input ="text" name="email"><br>
    Password: <input type="number" name="password"><br>
    Nif: <input type="number" name="nif"><br>
    Address: <input type="text" name="address"><br>
    Telephone: <input type="number" name="telephone"><br>
    Username: <input type="text" name="username"><br>
    Role: <input type="text" name="username"><br>
    Birthday: <input type="number" name="birthday"><br>
    <input type="submit">
</form>

</body>
</html>